networks:
  web:
    name: web
  intercom:
    name: intercom

volumes:
  order_pg_vol:
  minio_data:
  # todo

services:
  traefik:
    image: "traefik:v3.5.2"
    security_opt:
      - no-new-privileges:true
    command:
      - "--providers.file.filename=/etc/traefik/traefik-dynamic.yml"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:80"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # Mount the dynamic configuration file
      - "./traefik-dynamic.yml:/etc/traefik/traefik-dynamic.yml:ro"
    networks:
      - web

  orderservice:
    build: .
    restart: unless-stopped
    command: [ "/app/ordersystem" ]
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGPORT=5555
      - DB_HOST=order-postgres
      - S3_ACCESS_KEY_ID=root
      - S3_SECRET_ACCESS_KEY=verysecret
      - S3_ENDPOINT=order-minio:8500
    networks:
      - intercom
      - web

  sws:
    image: joseluisq/static-web-server:latest
    environment:
      - SERVER_PORT=80
      - SERVER_ROOT=/public
    volumes:
      - ./frontend:/public
    networks:
      - intercom
      - web

  order-postgres:
    image: postgres:18
    volumes:
      - order_pg_vol:/var/lib/postgresql
    restart: always
    networks:
      - intercom
    ports:
      - "5555:5555"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGPORT=5555

  order-minio:
    image: minio/minio:latest
    restart: always
    ports:
      - "8500:8500"
    networks:
      - intercom
    command: ["server", "--address", ":8500", "/data"]
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=verysecret

    # todo use minio/minio:latest as image
    # expose 8500
    # add to network intercom
    # use the following commands: "server", "--address", ":8500", "/data"
    # map the data volume
    # set environment variables MINIO_ROOT_USER and MINIO_ROOT_PASSWORD